//
//  MainPresenter.swift
//  wikiDog
//
//  Created by Daniel Romero on 25-11-19.
//  Copyright (c) 2019 Dromero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
  func presentFetchDogs(response: Main.Requestbreeds.Response)
  func presentSelectDog(response: Main.SelectBreeds.Response)
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?

  func presentFetchDogs(response: Main.Requestbreeds.Response)
  {
    
    let isError = response.isError
    let message = response.message
    let breeds  = response.breeds
    
    switch isError {
    case true:
      let viewModel = Main.Requestbreeds.ViewModel(breeds: breeds, message: message)
      viewController?.errorFetchDogs(viewModel: viewModel)
    default:
      let viewModel = Main.Requestbreeds.ViewModel(breeds: breeds, message: message)
      viewController?.successFetchDogs(viewModel: viewModel)
    }
  }
  
  func presentSelectDog(response: Main.SelectBreeds.Response)
  {
    let viewModel = Main.SelectBreeds.ViewModel()
    viewController?.successSelectDogs(viewModel: viewModel)
  }
}
