//
//  MainModels.swift
//  wikiDog
//
//  Created by Daniel Romero on 25-11-19.
//  Copyright (c) 2019 Dromero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum Main
{
  // MARK: Use cases
  enum Requestbreeds
  {
    struct Request
    {
    }
    struct Response
    {
      var breeds: Results<Breeds>
      var isError: Bool
      var message: String
    }
    struct ViewModel
    {
      var breeds: Results<Breeds>
      var message: String
    }
  }
  
  enum SelectBreeds
  {
    struct Request
    {
      var name: String
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
