//
//  MainWorker.swift
//  wikiDog
//
//  Created by Daniel Romero on 25-11-19.
//  Copyright (c) 2019 Dromero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class MainWorker
{
  func getBreeds(completionHandler: @escaping (_ isOk: Bool,_ breeds: NSDictionary,_ message: String) -> Void) {
     
     if Connectivity.isConnectedToInternet
     {
      _ = Alamofire.request(APIRouter.getDogs).responseJSON{ (response) in
         switch response.result{
         case .success(let value):
           
          let jsonValue = value as! [String: Any]
          let status = jsonValue["status"] as? String ?? ""
           
          if status == "success"
          {
            let breeds = jsonValue["message"] as! NSDictionary
            completionHandler(true,breeds,"")
          }else
          {
            completionHandler(false,[:],Constants.Messages.Api.serverErrorText)
          }
           
         case .failure:
          completionHandler(false,[:],Constants.Messages.Api.serverErrorText)
           break
         }
       }
     }else
     {
      completionHandler(false,[:],Constants.Messages.Api.internetText)
     }
     
   }
}
