# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wikiDog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wikiDog
  
  # Pods network
   pod 'Alamofire'
   # Pods Conection
   pod 'RealmSwift'
   # Pods Animations
   pod 'lottie-ios'
   # Pods Images
   pod 'Kingfisher'
   
  target 'wikiDogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wikiDogUITests' do
    # Pods for testing
  end

end
