//
//  DogsImagesWorker.swift
//  wikiDog
//
//  Created by Daniel Romero on 25-11-19.
//  Copyright (c) 2019 Dromero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class DogsImagesWorker
{
  func getImages(_ name: String,completionHandler: @escaping (_ isOk: Bool,_ ofmessage: String,_ images: NSArray?) -> Void) {

      if Connectivity.isConnectedToInternet
      {
        _ = Alamofire.request(APIRouter.getImages(name: name)).responseJSON{ (response) in
          switch response.result{
          case .success(let value):
            
            let jsonValue = value as! [String: Any]
            
            let status = jsonValue["status"] as? String ?? ""
            
            if status == "success"
            {
              let images = jsonValue["message"] as! NSArray
              completionHandler(true,"",images)
            }else
            {
              completionHandler(false,Constants.Messages.Api.serverErrorText,nil)
            }
          case .failure:
            completionHandler(false,Constants.Messages.Api.serverErrorText,nil)
            break
          }
        }
      }else
      {
          completionHandler(false,Constants.Messages.Api.internetText,nil)
      }
    }
}
