//
//  DogsImagesInteractor.swift
//  wikiDog
//
//  Created by Daniel Romero on 25-11-19.
//  Copyright (c) 2019 Dromero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol DogsImagesBusinessLogic
{
  func loadBreedsImages(request: DogsImages.Images.Request)
}

protocol DogsImagesDataStore
{
  var name: String { get set }
}

class DogsImagesInteractor: DogsImagesBusinessLogic, DogsImagesDataStore
{
  var presenter: DogsImagesPresentationLogic?
  var worker: DogsImagesWorker?
  var name: String = ""
  let realm = try! Realm()

  func loadBreedsImages(request: DogsImages.Images.Request)
  {
     worker = DogsImagesWorker()
     worker?.getImages(self.name)
       {[] (isOk,ofmessage,images) in
         switch isOk
         {
         case true:
          
           let breed = Breeds.query(name: self.name)
          
           let ofImages = self.realm.objects(BImages.self)
           try! self.realm.write
           {
             self.realm.delete(ofImages)
           }
           
           for image in images!
           {
             breed.addImage(link: image as! String)
           }
           
           let response = DogsImages.Images.Response(isError: false, message: "", breed: breed)
           self.presenter?.presentImagesDogs(response: response)
         case false:
           let breed = Breeds.query(name: self.name)
           let response = DogsImages.Images.Response(isError: true, message: ofmessage, breed: breed)
           self.presenter?.presentImagesDogs(response: response)
         }
     }
   }
}
