//
//  DogsImagesModels.swift
//  wikiDog
//
//  Created by Daniel Romero on 25-11-19.
//  Copyright (c) 2019 Dromero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DogsImages
{
  enum Images
   {
     struct Request
     {
     }
     struct Response
     {
       var isError: Bool
       var message: String
       var breed: Breeds
     }
     struct ViewModel
     {
       var message: String
       var breed: Breeds
     }
   }
}
